name: Setup Docker & Auth

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/matrix.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}

